export const stateTaxData = [
    { slug: "california", name: "California", rate: 7.25 },
    { slug: "new-york", name: "New York", rate: 4 },
    { slug: "texas", name: "Texas", rate: 6.25 },
    { slug: "florida", name: "Florida", rate: 6 },
    { slug: "illinois", name: "Illinois", rate: 6.25 },
    { slug: "pennsylvania", name: "Pennsylvania", rate: 6 },
    { slug: "ohio", name: "Ohio", rate: 5.75 },
    { slug: "georgia", name: "Georgia", rate: 4 },
    { slug: "north-carolina", name: "North Carolina", rate: 4.75 },
    { slug: "michigan", name: "Michigan", rate: 6 },
    { slug: "new-jersey", name: "New Jersey", rate: 6.625 },
    { slug: "virginia", name: "Virginia", rate: 5.3 },
    { slug: "washington", name: "Washington", rate: 6.5 },
    { slug: "arizona", name: "Arizona", rate: 5.6 },
    { slug: "massachusetts", name: "Massachusetts", rate: 6.25 },
    { slug: "tennessee", name: "Tennessee", rate: 7 },
    { slug: "indiana", name: "Indiana", rate: 7 },
    { slug: "missouri", name: "Missouri", rate: 4.225 },
    { slug: "maryland", name: "Maryland", rate: 6 },
    { slug: "wisconsin", name: "Wisconsin", rate: 5 },
    { slug: "colorado", name: "Colorado", rate: 2.9 },
    { slug: "minnesota", name: "Minnesota", rate: 6.875 },
    { slug: "south-carolina", name: "South Carolina", rate: 6 },
    { slug: "alabama", name: "Alabama", rate: 4 },
    { slug: "louisiana", name: "Louisiana", rate: 4.45 },
    { slug: "kentucky", name: "Kentucky", rate: 6 },
    { slug: "oregon", name: "Oregon", rate: 0 },
    { slug: "oklahoma", name: "Oklahoma", rate: 4.5 },
    { slug: "connecticut", name: "Connecticut", rate: 6.35 },
    { slug: "utah", name: "Utah", rate: 4.85 },
    { slug: "nevada", name: "Nevada", rate: 6.85 },
    { slug: "arkansas", name: "Arkansas", rate: 6.5 },
    { slug: "mississippi", name: "Mississippi", rate: 7 },
    { slug: "kansas", name: "Kansas", rate: 6.5 },
    { slug: "new-mexico", name: "New Mexico", rate: 5.125 },
    { slug: "nebraska", name: "Nebraska", rate: 5.5 },
    { slug: "west-virginia", name: "West Virginia", rate: 6 },
    { slug: "idaho", name: "Idaho", rate: 6 },
    { slug: "hawaii", name: "Hawaii", rate: 4 },
    { slug: "maine", name: "Maine", rate: 5.5 },
    { slug: "new-hampshire", name: "New Hampshire", rate: 0 },
    { slug: "rhode-island", name: "Rhode Island", rate: 7 },
    { slug: "montana", name: "Montana", rate: 0 },
    { slug: "delaware", name: "Delaware", rate: 0 },
    { slug: "south-dakota", name: "South Dakota", rate: 4.5 },
    { slug: "north-dakota", name: "North Dakota", rate: 5 },
    { slug: "alaska", name: "Alaska", rate: 0 },
    { slug: "vermont", name: "Vermont", rate: 6 },
    { slug: "wyoming", name: "Wyoming", rate: 4 },
    { slug: "district-of-columbia", name: "District of Columbia", rate: 6 },
  ];