// src/app/blog/content/random-number-generation-explained.tsx
export default function Post() {
  return (
    <>
      <p>
        "Pick a random number between 1 and 100" sounds trivial, but the
        difference between a genuinely random number and one that only seems
        random is important in security, statistics, simulations, and games.
        Understanding what makes a number generator truly random, and when
        "random enough" is actually fine, helps you use randomness correctly
        across different contexts.
      </p>

      <h2>True random vs pseudorandom</h2>
      <p>
        <strong>True random numbers</strong> are generated from physical
        processes thermal noise, radioactive decay, photon behaviour. They're
        unpredictable in principle, not just in practice. Hardware random number
        generators (HRNGs) and services like random.org produce true random
        numbers.
      </p>
      <p>
        <strong>Pseudorandom numbers</strong> are generated by deterministic
        algorithms starting from a seed value. Given the same seed, the same
        sequence is produced every time. They appear random to statistical tests
        but are entirely predictable if you know the algorithm and seed. Most
        software random functions (Python's <code>random</code>, JavaScript's{" "}
        <code>Math.random()</code>) are pseudorandom.
      </p>
      <p>
        <strong>Cryptographically secure pseudorandom numbers</strong> (CSPRNGs)
        use seeding from entropy sources (system events, hardware noise) and
        algorithms designed to be computationally infeasible to predict even if
        you know some outputs. Used for security-critical applications.
      </p>
      <p>
        Our <a href='/tools/random-number-generator'>Random Number Generator</a>{" "}
        generates random numbers in any range using a cryptographically secure
        source.
      </p>

      <h2>When pseudorandom is fine</h2>
      <p>
        For the vast majority of uses, standard pseudorandom generators are
        perfectly adequate:
      </p>
      <ul>
        <li>
          Games and simulations (dice rolls, shuffling cards, procedural
          generation)
        </li>
        <li>
          Statistical sampling and research (choosing random participants,
          random assignment in experiments)
        </li>
        <li>
          UI/UX randomisation (showing different content to different users)
        </li>
        <li>Random test data generation</li>
        <li>Picking a random winner from a list</li>
      </ul>

      <h2>When you need a CSPRNG</h2>
      <p>Security applications require cryptographically secure randomness:</p>
      <ul>
        <li>Generating passwords, tokens, or session IDs</li>
        <li>Cryptographic key generation</li>
        <li>OAuth state parameters and CSRF tokens</li>
        <li>Any value where predictability could enable an attack</li>
      </ul>
      <p>
        Using a weak PRNG for security purposes is a real vulnerability. Many
        historical security breaches exploited predictable "random" values. In
        code: use <code>secrets</code> module in Python,{" "}
        <code>crypto.getRandomValues()</code> in JavaScript,{" "}
        <code>SecureRandom</code> in Java not the standard random functions.
      </p>

      <h2>Generating random numbers in a custom range</h2>
      <p>To generate a random integer between min and max (inclusive):</p>
      <p>Random integer = min + floor(random() × (max − min + 1))</p>
      <p>
        Where <code>random()</code> returns a float between 0 (inclusive) and 1
        (exclusive).
      </p>
      <p>
        Example for 1–100: 1 + floor(random() × 100). For 50–75: 50 +
        floor(random() × 26).
      </p>

      <h2>Common use cases</h2>

      <h3>Picking a random winner</h3>
      <p>
        Assign each entry a number (1 to N), generate a random number in that
        range, select the corresponding entry. For fair giveaways, use a
        publicly observable random source (dice, live broadcast) or a verifiably
        random service so results can be independently verified.
      </p>

      <h3>Random sampling</h3>
      <p>
        In research and data analysis, random sampling requires that every item
        in a population has an equal probability of selection. Standard
        pseudorandom generators are appropriate for this the predictability is
        irrelevant since the research outcome doesn't depend on the specific
        seed.
      </p>

      <h3>Randomised A/B testing</h3>
      <p>
        Assigning users to test variants requires a consistent, unbiased
        assignment that's deterministic per user (user always sees the same
        variant) but random across users. Hashing the user ID with a variant
        seed is a common approach.
      </p>

      <h2>FAQ</h2>

      <h3>Is a dice roll truly random?</h3>
      <p>
        In principle, a dice roll is deterministic given perfect knowledge of
        all physical variables (angle, force, surface friction), you could
        predict the outcome. In practice, the variables are unknowable, making
        it effectively random. Physical processes like dice rolls and coin flips
        are good sources of unpredictable randomness for everyday use.
      </p>

      <h3>Why do random number generators need seeds?</h3>
      <p>
        A PRNG algorithm produces a sequence deterministically from a starting
        value (the seed). Without a varying seed, the same sequence would be
        produced every time the program runs. Seeds are typically taken from
        system entropy current time, memory addresses, mouse movements to
        produce different sequences each run.
      </p>

      <h3>How do I generate a random number without repeats?</h3>
      <p>
        Generate all numbers in the range, shuffle the list (Fisher-Yates
        algorithm), then take numbers from the shuffled list in order. This
        guarantees no repeats while maintaining uniform distribution.
      </p>

      <h2>Conclusion</h2>
      <p>
        Most everyday random number needs are well-served by a standard random
        number generator. For security applications, always use a
        cryptographically secure source. Use the{" "}
        <a href='/tools/random-number-generator'>Random Number Generator</a> for
        instant random numbers in any custom range from a single number to large
        batches.
      </p>
    </>
  );
}
