// src/app/tools/totp-code-generator/page.tsx
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { tools } from "@/lib/tools";

const TotpCodeGeneratorClient = dynamic(
  () => import("./TotpCodeGeneratorClient"),
  {
    loading: () => (
      <div className="min-h-[420px] bg-gray-50 rounded-2xl animate-pulse" />
    ),
  },
);
import SidebarAdLayout from "@/components/SidebarAdLayout";
import PageEditorial from "./PageEditorial";
import ToolEngagement from "@/components/ToolEngagement";
const tool = tools.find((t) => t.slug === "totp-code-generator");

const SITE_URL = "https://www.onlinetoolbase.com";
const SITE_NAME = "OnlineToolBase";

export const metadata: Metadata = {
  title: "TOTP / 2FA Code Generator — Test Authenticator Codes",
  description:
    "Generate live time-based one-time passcodes (TOTP) from a Base32 secret key, entirely in your browser. Useful for testing 2FA setups. Free, no signup.",
  keywords:
    "totp generator, 2fa code generator, authenticator code generator, totp code, two factor authentication tester, otp generator",
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  alternates: { canonical: `${SITE_URL}/tools/totp-code-generator` },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    url: `${SITE_URL}/tools/totp-code-generator`,
    siteName: SITE_NAME,
    locale: "en_US",
    title: "TOTP / 2FA Code Generator — Test Authenticator Codes",
    description:
      "Generate live TOTP codes from a Base32 secret, entirely client-side. Free, no signup.",
    images: [
      {
        url: `${SITE_URL}/opengraph-image`,
        width: 1200,
        height: 630,
        alt: "Free TOTP / 2FA Code Generator",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@onlinetoolbase",
    creator: "@onlinetoolbase",
    title: "TOTP / 2FA Code Generator — Test Authenticator Codes",
    description:
      "Generate live authenticator app codes from a secret key. Fully offline. Free.",
  },
};

const toolJsonLd = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "TOTP / 2FA Code Generator",
  description:
    "Generates time-based one-time passcodes (TOTP, RFC 6238) from a Base32-encoded secret key using the Web Crypto API's HMAC implementation, entirely in the browser. Supports 6 or 8 digit codes, 30 or 60 second periods, and SHA-1/SHA-256/SHA-512 algorithms.",
  url: `${SITE_URL}/tools/totp-code-generator`,
  applicationCategory: "SecurityApplication",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
    availability: "https://schema.org/InStock",
  },
  provider: { "@type": "Organization", name: SITE_NAME, url: SITE_URL },
};
const breadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
    {
      "@type": "ListItem",
      position: 2,
      name: "Security Tools",
      item: `${SITE_URL}/tools/category/security-tools`,
    },
    {
      "@type": "ListItem",
      position: 3,
      name: "TOTP / 2FA Code Generator",
      item: `${SITE_URL}/tools/totp-code-generator`,
    },
  ],
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is a TOTP code?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "TOTP (Time-based One-Time Password) is the standard behind the six-digit codes generated by apps like Google Authenticator and Authy. It's computed from a shared secret key and the current time, refreshing on a fixed interval (usually every 30 seconds), as defined in RFC 6238.",
      },
    },
    {
      "@type": "Question",
      name: "Where do I find my Base32 secret key?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "When a service sets up two-factor authentication, it usually shows a QR code plus a 'can't scan this?' option that reveals the same secret as text — a string of letters and digits. That text string is what you'd paste into this tool.",
      },
    },
    {
      "@type": "Question",
      name: "Is it safe to enter a 2FA secret here?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "The secret is processed entirely in your browser and never transmitted anywhere — codes are computed locally using the Web Crypto API. That said, treat any 2FA secret like a password: only enter secrets you own, and avoid pasting one into any tool if you're not confident about how it handles data.",
      },
    },
    {
      "@type": "Question",
      name: "Why doesn't my generated code match my authenticator app?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "The most common cause is your device's clock being out of sync — TOTP depends on accurate time. Also double-check the digit count, period, and algorithm match what the service expects; most use 6 digits, 30 seconds, and SHA-1.",
      },
    },
  ],
};

const howToJsonLd = {
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to Use the TOTP / 2FA Code Generator",
  description:
    "Step-by-step guide to using the free TOTP / 2FA Code Generator on Calculators, Pdf Tools & More.",
  step: [
    {
      "@type": "HowToStep",
      position: 1,
      name: "Enter your Base32 secret",
      text: "Paste the secret key shown when a service set up two-factor authentication.",
    },
    {
      "@type": "HowToStep",
      position: 2,
      name: "Watch the live code",
      text: "A 6- or 8-digit code appears and refreshes automatically on the countdown.",
    },
    {
      "@type": "HowToStep",
      position: 3,
      name: "Copy the code",
      text: "Copy the current code to use before it expires.",
    },
  ],
};

export default function TotpCodeGeneratorPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(toolJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToJsonLd) }}
      />
      <nav aria-label="Breadcrumb" className="max-w-6xl mx-auto px-4 pt-4 pb-2">
        <ol className="flex items-center gap-2 text-sm text-gray-500">
          <li>
            <a href="/" className="hover:text-cyan-600 transition-colors">
              Home
            </a>
          </li>
          <li aria-hidden="true" className="text-gray-300">
            /
          </li>
          <li>
            <a
              href="/tools/category/security-tools"
              className="hover:text-cyan-600 transition-colors"
            >
              Security Tools
            </a>
          </li>
          <li aria-hidden="true" className="text-gray-300">
            /
          </li>
          <li>
            <span aria-current="page" className="text-gray-900 font-medium">
              TOTP / 2FA Code Generator
            </span>
          </li>
        </ol>
      </nav>
      <header className="max-w-6xl mx-auto px-4 pt-2 pb-0">
        <p className="text-xs font-semibold text-cyan-600 uppercase tracking-widest mb-1">
          Free Security Tool · No Signup · Works Instantly
        </p>
        <h1 className="text-2xl font-bold text-gray-900 mb-1">
          TOTP / 2FA Code Generator — Test Authenticator Codes
        </h1>
        <p className="text-sm text-gray-500 max-w-2xl mb-2">
          Generate live time-based one-time codes from a Base32 secret key —
          entirely offline in your browser.
        </p>
      </header>
      <SidebarAdLayout tool={tool}>
        <main id="main-content" aria-label="TOTP / 2FA Code Generator tool">
          <TotpCodeGeneratorClient />
        </main>
        <PageEditorial />
        <ToolEngagement
          toolSlug="totp-code-generator"
          toolName="TOTP / 2FA Code Generator"
        />
      </SidebarAdLayout>
    </>
  );
}
